name: credit_risk_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7  # JANGAN DIHAPUS, biarkan tetap begini
  - pip
  - pip:
      - mlflow==2.19.0 # Sesuai ketentuan
      - scikit-learn
      - pandas
      - joblib
      - dagshub
      - matplotlib