name: MLflow Project CI

on: [push]

jobs:
  run-ml-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
          
      - name: Install MLflow
        run: pip install mlflow pandas scikit-learn dagshub
        
      - name: Run MLflow Project
        run: |
          # Perintah ini akan mengecek apakah MLProject valid dan bisa jalan
          mlflow run MLProject --experiment-name "CI_Workflow_Muhammad-Restu-Ilahi" --no-conda