name: MLflow Project CI

on: [push]

permissions:
  contents: write

jobs:
  run-ml-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'
          
      - name: Install All Dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn dagshub joblib virtualenv
          
      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/mrestuilahi1405/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          mlflow run MLProject --experiment-name "CI_Workflow_Muhammad-Restu-Ilahi" --run-name "CI_Workflow_Muhammad-Restu-Ilahi_Run_v${{ github.run_number }}" --env-manager local

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-run-${{ github.run_number }}
          path: artifacts/
          retention-days: 7

      - name: Commit and Push Artifacts to Repository
        run: |
          # Konfigurasi identitas bot GitHub
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Tambahkan folder artifacts ke staging area
          git add artifacts/
          
          # Melakukan commit. 
          git commit -m "chore: update production artifacts from run ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          
          # Push kembali ke branch main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/mrestuilahi1405/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          # Build menggunakan Model Registry (latest)
          mlflow models build-docker -m "models:/model_credit_risk/latest" -n "mrestuilahi1405/credit-risk-app:latest" --enable-mlserver
          
          docker push mrestuilahi1405/credit-risk-app:latest